language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t khu021a/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true khu021a/react-test npm run test

after_success:
  - docker build -t khu021a/multi-client ./client
  - docker build -t khu021a/multi-nginx ./nginx
  - docker build -t khu021a/multi-server ./server
  - docker build -t khu021a/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push khu021a/multi-client
  - docker push khu021a/multi-nginx
  - docker push khu021a/multi-server
  - docker push khu021a/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-724434728004"
  bucket_path: "docker-multi"
  on: 
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"